nissl-lab/npoi

- main/main vs10.csproj
- ooxml/OpenXmlFormats/OpenXmlFormats vs2010.csproj
The build is currently broken for the vs2010 solution. New files were committed and used without adding the files to the appropriate projects. Additionally, one of the projects was changed from .NET 4.0 to .NET 2.0 even though it is referencing other .NET 4.0 projects.
> Add missing files to vs2010 projects to fix build

- main/HSSF/UserModel/HSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFCellStyle.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
1. Copying the PageSetup works flawlessly, which is why that block can be removed. With that block, I always get the NotImplementedException, so an Exception which has no benefit.
2. The XSSFHyperlink collection needs to be copied. Otherwise, the links are not displayed in the duplicated sheet but Excel throws a parsing error upon opening the workbook.
3. When hyperRel is null, it is better to cancel adding this hyperlink than canceling the whole process. With the addition of point 2., the links are shown anyway.
> Fix CopySheet()

- main/main vs10.csproj
- ooxml/OpenXmlFormats/OpenXmlFormats vs2010.csproj
- ooxml/OpenXmlFormats/Spreadsheet/Styles/CT_CellAlignment.cs
The default vertical alignment in Excel for XLSX files is bottom, not center. Additionally, this value is never written to styles.xml by Excel (Even when the user manually selects it).
Default cell format:
<cellXfs count="1">
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
</cellXfs>
Manually set Vertical=Bottom and Horizontal=Left:
<cellXfs count="2">
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1">
<alignment horizontal="left"/>
</xf>
</cellXfs>
> Fix XLSX default vertical alignment

- main/HSSF/UserModel/HSSFWorkbook.cs
When Windows attempts to enforce FIPS, it disallows all usage of the MD5. Using SHA1 here will make it work.
> HSSFWorkbook: Use SHA1 in AddPicture when running under FIPS.

- ooxml/OOXML.csproj
- ooxml/OpenXmlFormats/Spreadsheet/SharedStringTable.cs
This will fix OOXML `CT_PhoneticRun` handling.
NPOI may break xlsx files that contain phonetic guides (furigana) information.
I do `(new XSSFWorkbook(fileWithFurigana)).Write(output)`, and then open the `output` file in Excel, Excel says:
> Excel found unreadable content in output.xlsx. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes.
If _Yes_ is selected, the file can be opened but its content becomes empty.
> Fix phonetic guides reading/writing issue

- ooxml/XSSF/UserModel/XSSFSheet.cs
I made a couple changes in the way XSSF sheet protection is setup and controlled.
First:
Fixed `XSSFSheet.LockFormatCells()`. The method was setting an incorrect property, `CT_SheetProtection.deleteColumns` instead of `CT_SheetProtection.formatCells`. 
Second:
By default, if sheet protection is enabled (`XSSFSheet.EnableLocking()`), most of the features are locked right away since corresponding properties have their default value set to true by `[DefaultValue(true)]` attribute.
Properties:
* `CT_SheetProtection.autoFilter`
* `CT_SheetProtection.deleteColumns`
* `CT_SheetProtection.deleteRows`
* `CT_SheetProtection.formatCells`
* `CT_SheetProtection.formatColumns`
* `CT_SheetProtection.formatRows`
* `CT_SheetProtection.insertColumns`
* `CT_SheetProtection.insertHyperlinks`
* …
> Fix of the way XSSF sheet protection properties are set up

- ooxml/OpenXmlFormats/Spreadsheet/Styles/CT_Border.cs
- ooxml/OpenXmlFormats/Spreadsheet/Styles/CT_BorderPr.cs
- ooxml/OpenXmlFormats/Spreadsheet/Styles/CT_Colors.cs
- ooxml/XSSF/UserModel/XSSFCellStyle.cs
XSSF border style caching is returning a reference to the original CT_Border object when modifying a cellstyle border property. This can result in a previous CT_Border being reused and then modified (without user being aware or being able to avoid), producing incorrect results.
Example to reproduce (In an ASP.net):
```
var book = new XSSFWorkbook();
var sheet = book.CreateSheet("Sheet1");
var row = sheet.CreateRow(1);
{
var cell = row.CreateCell(1);
var cellStyle = book.CreateCellStyle();
cellStyle.BorderTop = NPOI.SS.UserModel.BorderStyle.Thin;
cell.CellStyle = cellStyle;
}
{
var cell = row.CreateCell(2);
var cellStyle = book.CreateCellStyle();
cellStyle.BorderTop = NPOI.SS.UserModel.BorderStyle.Thin;
cellStyle.BorderRight = NPOI.SS.UserModel.BorderStyle.Thin;
cell.CellStyle = cellStyle; …
```
> Fixing weird XSSF CellStyle Border behaviour..

- ooxml/OpenXmlFormats/Spreadsheet/Workbook.cs
The problem is describben here by someone else:
http://npoi.codeplex.com/discussions/647190
So this just impacts if you are using an already existing Excel file to start with.
If you create a new Excel file fullPrecision is always true, but the property is not set in the workbook.xml file. So when we read the template and the property is not there the default value is then set to false, but in my opinion it should be true to be consistent with creating a new Excel file.
> Set fullPrecision default to true as it is for a new Excel file

- ooxml/XSSF/UserModel/XSSFWorkbook.cs
Added check for existence of ctSheet.id in shIdMap dictionary before get.
Library raised System.Collections.Generic.KeyNotFoundException when opening some xlsm files.
> Check key in shIdMap

- ooxml/OpenXmlFormats/Vml/Main.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFVMLDrawing.cs
Original symptom: Comments in *.xlsx files had no background color and were difficult to read.
It looks like there's a problem reading/writing CT_Shapetype .filled and .stroked fields.  This occurs because CT_Shapetype.Write() defaults .stroked and .filled values to true, but the CT_Shapetype class defaults these values to false.
I've updated the CT_Shapetype class to default these two values to true.  
This fixed the original symptom by removing filled="false" and stroked="false" in the shapetype tag corresponding to comments in the *.xlsx file at: "xl\drawings\vmlDrawing1.vml".  This un-hid the square background box that OOXML was trying to draw behind comments.
> CT_Shapetype defaults fixed to fix cell comments

- .gitignore
- testcases/main/NPOI.TestCases.csproj
- testcases/main/SS/UserModel/BaseTestConditionalFormatting.cs
- testcases/main/packages.config
- testcases/ooxml/NPOI.OOXML.TestCases.csproj
- testcases/ooxml/packages.config
- testcases/openxml4net/NPOI.OOXML4Net.Testcases.csproj
- testcases/openxml4net/packages.config
This changes allows us to executing unit tests on Visual Studio Test Explorer **without installing any extensions** such as NUnit test runner extension for Visual Studio.
Anybody who using Visual Studio 2012 or above can execute unit tests immediately after only `git clone`.
This feature helps committers to executing unit tests with any changes/commits, because there are no need to preparing - such as installing some Visual Studio extensions - for executing unit tests.
> Bundle NUnit Test Adapter into projects via NuGet.

- ooxml/openxml4Net/OPC/ZipPackage.cs
- solution/Lib/RunSerialyAndSweepTmpFilesAttribute.cs
- testcases/ooxml/NPOI.OOXML.TestCases.csproj
- testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
- testcases/openxml4net/NPOI.OOXML4Net.Testcases.csproj
- testcases/openxml4net/OPC/Compliance/TestOPCComplianceCoreProperties.cs
- testcases/openxml4net/TestPackage.cs
We can reproduce the bug by simple code that only open and close .xlsx file like this:
```csharp
var baseDir = AppDomain.CurrentDomain.BaseDirectory;
var path = Path.Combine(baseDir, "Book1.xlsx");
var book = WorkbookFactory.Create(path);
book.Close();
```
After `book.Close()` method was invoked, temporary file ("OpenXml4Net~.tmp") was created and remain even after program exited.
At first, I wrote improving unit test code to detect temporary files remain or not. (commit 		0c512ad )
This change effect 7 test cases from "passed" to "failed".
You can get those 7 test cases from ".playlist" file below:
Download: ["The bug that temporary files remain.playlit.zip"](https://github.com/tonyqus/npoi/files/760650/The.bug.that.temporary.files.remain.playlit.zip)
Next step, I fixed "ZipPackage.cs". …
> Fix: Temporary files remain when ZipPackage closed.

- ooxml/OpenXmlFormats/Wordprocessing/FormField.cs
- ooxml/OpenXmlFormats/Wordprocessing/HdrFtr.cs
- ooxml/OpenXmlFormats/Wordprocessing/Paragraph.cs
- ooxml/OpenXmlFormats/Wordprocessing/Run.cs
Found that while saving a word document (docx) NPOI make some exception. 
This was due to fields feature. Some XML tags that was wrongly formated and a bad type for enabled parameter.
Then when fixed, found also that there was some issu with the layout. It was missing to write the attribute 'after' event if value equals to 0.
> Word processing fields issue

- ooxml/OpenXmlFormats/Spreadsheet/AutoFilter.cs
- ooxml/openxml4Net/Util/XmlHelper.cs
Fixed issues with writing Table AutoFilters to XML. Excel 2013 will not read a file where the autoFilter colId is not specified. NPOI was not writing this when the colId was 0. 
Below is an example file where I was having the issue. Just creating a XSSFWorkbook from a stream and writing it back out produces this error (see attached).
[MikaelTest.xlsx](https://github.com/tonyqus/npoi/files/1648149/MikaelTest.xlsx)
I'm not entirely sure how to write a unit test for this since the method I changed writes to a StreamWriter. Any tips here?
> Fix: AutoFilter colId is required even when 0

- main/SS/UserModel/DataFormatter.cs
In Java POI, 'ddd' and 'dddd' of Excel day of the week are converted to Java 'EEE', 'EEEE', but in C# 'ddd', 'dddd' directly outputs the days of the week.
Currently 'EEEE' will be displayed as it is, so should not be replaced.
/main/SS/UserModel/DataFormatter.cs
```csharp
79:         /** Pattern to find days of week as text "ddd...." */
80:         private static string daysAsText = "([d]{3,})";
----
421:             MatchCollection match = Regex.Matches(formatStr, daysAsText);
422:             if (match.Count > 0)
423:             {
424:                 string replacement = match[0].Groups[0].Value.ToUpper().Replace("D", "E");
425:                 formatStr = Regex.Replace(formatStr, daysAsText, replacement);
426:             }
```
Current output.
```
EEEE, June 01, 2017
```
Delete …
> Delete conversion of day format 'dddd' to 'EEEE' in date format.

- OpenXmlFormats/NPOI.OpenXmlFormats.Core.csproj
- main/NPOI.Core.csproj
- ooxml/NPOI.OOXML.Core.csproj
- openxml4Net/NPOI.OpenXml4Net.Core.csproj
This change allows .NET Framework applications to pull in the same class libraries -- the same binaries -- as a .NET Core application could, so that compatibility is increased.
This is an initial change; it's possible that a lower (i.e., more universal) version of .NET Standard could be used, but this is a starting point.
> Convert .NET Core class libraries to .NET Standard

- ooxml/XSSF/UserModel/XSSFSheet.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheetShiftRows.cs
Bug reported here: https://bz.apache.org/bugzilla/show_bug.cgi?id=57423
Simple bugfix where CT_Rows are sorted at the end of ShiftRows().
> Fix POI bug 57423 ShiftRows() produces a corrupted xlsx file

- ooxml/XSSF/UserModel/XSSFWorkbook.cs
Add a null check in IsDate1904(), returning the false default.
Needed for some computer generated xlsx files, which are missing this information and causing exceptions in this method.
> Update XSSFWorkbook.cs - IsDate1904()

- ooxml/XSSF/UserModel/XSSFFont.cs
Addressed by performing a null check before trying to clone style. 
After further testing, it also appears that this is a source for not just errors here, but was also causing corrupted xlsx files to be created.
> #201 - XSSFFont CloneStyleFrom generates NPE if passed in src is null

- OpenXmlFormats/Wordprocessing/Document.cs
- OpenXmlFormats/Wordprocessing/Paragraph.cs
- ooxml/POIXMLDocumentPart.cs
- ooxml/XWPF/Usermodel/XWPFDocument.cs
- ooxml/XWPF/Usermodel/XWPFParagraph.cs
Example:
```c#
foreach (XWPFParagraph par in newDoc.Paragraphs)
{
// Double Space
par.SpacingBetween = 480;
}
```
Similar to Apache Poi
[XWPF.setSpacingBetween(double spacing)](https://poi.apache.org/apidocs/dev/org/apache/poi/xwpf/usermodel/XWPFParagraph.html#setSpacingBetween-double-)
> added SpacingBetween (XWPFParagraph)

- ooxml/XSSF/Extractor/XSSFExcelExtractor.cs
- testcases/ooxml/XSSF/Extractor/TestXSSFExcelExtractor.cs
The default IRow enumerator will skip empty cells. This makes it so that the output from the Text property has cells that don't line up with their corresponding headers.
This fix calls GetCell instead, which will return null in cases where the cell was empty. The tab delimiters work as expected now.
> Fix XSSFExcelExtractor to emit empty cells

- ooxml/XSSF/UserModel/XSSFHyperlink.cs
Fix URI with Chinese Charset Issue
string path = @"Test/測試.pdf";
if (Uri.TryCreate(path, UriKind.RelativeOrAbsolute, out Uri myUri))
{
Console.Write("OK");
}
var newPath = Uri.EscapeUriString(path);
bool isWellFormedUriString = Uri.IsWellFormedUriString(newPath, UriKind.RelativeOrAbsolute);
> Fix URI with Chinese Charset Issue

- ooxml/XSSF/UserModel/XSSFDataValidationHelper.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFDataValidation.cs
Multiple CellRangeAddresses can be used for XSSFDataValidation.CreateValidation, but only the last one is used.
> Fix XSSFDataValidationHelper.CreateValidation to use all CellRangeAddresses.

- ooxml/XSSF/UserModel/XSSFSheet.cs
- solution/NPOI.sln
CreateRow in the XSSFSheet is slow when you want to insert a lot of rows in the middle of a spreadsheet.
I profiled a test and figured out that "HeadMap" is creating a full copy of the elements, but in the end only the number is needed
Since I found no other usage of that method I replaced it with a version that only counts and my test was running in about 2s, before it took 8s.
Also memory usage should be a little bit better.
> improve performance of CreateRow for bigger excel sheets

- main/SS/UserModel/DateUtil.cs
- main/Util/LocaleUtil.cs
Hi, I found a bug in LocaleUtil.cs, which leads to a NullReferenceException in multi-threaded environments.
Since the TimeZone class is marked obsolete, i also changed all references to this class to TimeZoneInfo.
The original Methods are left intact, but all marked obsolete.
> Bug found in LocaleUtil.cs. 

- OpenXmlFormats/Spreadsheet/SharedString/CT_Rst.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFRichTextString.cs
Fixed shared string hash for texts with the color set as RGB so they are considered different strings if the color is different. This fixes the issue mentioned in #211 .
> fix: Rich strings hash for texts with the color set as RGB

- main/SS/UserModel/IndexedColors.cs
> Fixed typo in indexed color ("lemonchilffon" instead of "lemonchiffon")

- main/SS/Formula/Atp/AnalysisToolPak.cs
- main/SS/Formula/Atp/Ifs.cs
- main/SS/Formula/Atp/Maxifs.cs
- main/SS/Formula/Atp/MinIfs.cs
- main/SS/Formula/Functions/Averageifs.cs
- main/SS/Formula/Functions/Sumifs.cs
- testcases/main/SS/Formula/Atp/TestIfs.cs
- testcases/main/SS/Formula/Atp/TestMaxIfs.cs
- testcases/main/SS/Formula/Atp/TestMinifs.cs
These new functions were added in Office 2019. They have not yet been mapped to POI, but I thought I would add them here first 😄 
Added support for:
- ifs
- minifs
- maxifs
Added tests for the above.
Added predicate checks to the above, and to averageifs
Tested and working on macOS and Linux.
It would be much appreciated if you could add the `hacktoberfest-accepted` label to this PR. I believe that this is a valid contribution to the NPOI project, and this label will indicate this to the Hacktoberfest event.
> Add ifs, maxifs, minifs functions to analysis tool pack

- ooxml/XSSF/Streaming/SXSSFRow.cs
- ooxml/XSSF/Streaming/SheetDataWriter.cs
As title, this PR fixed #436 issue.
> 	fix issue #436 skipped cell issue

- ooxml/XWPF/Usermodel/XWPFParagraph.cs
- testcases/ooxml/XWPF/UserModel/TestXWPFParagraph.cs
Bug Cases:
Four runs in paragraph:
["abc","de","f","g"]
Search 'cdefg'
First run, 'c' was found and beginCharPos = 2.
Second run, the beginCharPos been set to 0 again.
In the end, the function will return 
{
Run = 0,
Text = 0,
Char = 0
}
However, the result should be 
{
Run = 0,
Text = 0,
Char = 2
}
The pull request fix this bug.
XWPFParagraph SearchIndex In Several Paragraph Reset BeginCharPos Each Time Move To Next Run
> Fix Bug: Paragraph ReplaceText/SearchText In Several Runs

- ooxml/XSSF/Streaming/SXSSFRow.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/Streaming/SheetDataWriter.cs
> SXSSFWorkbook possible performance overhead #434

- main/SS/Formula/Atp/IfError.cs
- main/SS/Formula/Functions/Match.cs
Wrong calculation of IFERROR and Match function  when missing argument
> Bug Fix: Wrong calculation of IFERROR and Match function 

- main/SS/Format/CellFormatPart.cs
- main/Util/CodePageUtil.cs
- testcases/main/HSSF/UserModel/TestSanityChecker.cs
This PR fixes a few small issues with unit tests that result in tests not being able to run on Linux and macOS using dotnet core.
- Fixes an infinite loop resulting from replacing null terminator within strings
- Registers the code page provider within the CodePageUtil to ensure availability in dotnet standard
- Corrects missing checks in the test sanity checker and removes unsafe thread usage
It would be much appreciated if you could add the `hacktoberfest-accepted` label to this PR. I believe that this is a valid contribution to the NPOI project, and this label will indicate this to the Hacktoberfest event.
> Ensure tests run linux and macOS

- OpenXmlFormats/Drawing/SpreadsheetDrawing.cs
Fixed a bug in XML generated for drawings with absolute cell anchor.
> fix CT_AbsoluteCellAnchor.Write

- ooxml/XSSF/Extractor/XSSFExcelExtractor.cs
- testcases/ooxml/XSSF/Extractor/TestXSSFExcelExtractor.cs
This fixes the issue addressed in PR #241 to emit a tab when an empty cell is encountered. Without it, any Excel file with an empty cell cannot be effectively parsed as CSV (TSV) since the cells don't line up with their expected columns. This fix does not affect any other tests.
> Fix XSSFExcelExtractor regression to emit empty cells

- main/Util/TempFile.cs
修复文件夹路径拼写问题，单反斜杠（Windows），单斜杠（Linux）。
在 Linux 系统下，会错误的创建名称为 \poifiles 文件夹，并且将临时文件直接存储到到 /tmp 目录下面，并非 /tmp/poifiles 目录。
BUG 截图
[![](https://attach.itsvse.com/bug/bug.jpg)](https://attach.itsvse.com/bug/bug.jpg)
修复后
[![](https://attach.itsvse.com/bug/fixedbug.jpg)](https://attach.itsvse.com/bug/fixedbug.jpg)
从 Windows 和 Linux 测试通过。
> 修复文件夹路径拼写问题，单反斜杠（Windows），单斜杠（Linux）

- ooxml/XSSF/UserModel/XSSFFont.cs
As reported here #317, the `CloneStyleFrom` method on `XSSFFont` copies the internal reference across, instead of copying over its attributes. This can lead to unexpected mutations.
> XSSFFont.CloneStyleFrom now always clones

- ooxml/XSSF/UserModel/XSSFCellStyle.cs
GetCTBorder() returns a shared instance when applyBorder is true. When GetCTBorder() is invoked from inside a property setter, that shared instance is then mutated and all other XSSFCellStyle instances that referred to the original (before mutation) CT_Border are changed as well. This appears to be unintentional. If we know we are inside a setter (and therefore about to mutate the state of the CT_Border) then we should perform that mutation on a copy.
> Get a copy of the CT_Border when about to mutate it

- OpenXmlFormats/Spreadsheet/AutoFilter.cs
Certain `AutoFilter` objects (re)written by NPOI are rejected by Office 365 Excel.
It turns out that the order of the children element within the `CT_AutoFilter` schema matters
and `filterColumn` must come before `sortState`.
> Fix the order of children of the AutoFilter xml element

- main/SS/Formula/Functions/Sumifs.cs
When I call `EvaluateAllFormulaCells` to evaluate, if the target `MatchPredicate` cell has no value, A `NullReferenceException` will be thrown and the program can't continue, so add the null check code.
> Add null check

- main/SS/Util/SheetUtil.cs
GetColumnWidth can be speeded up for big sheets if we explore for example only the first 100 rows!
> GetColumnWidth: no need to explore the whole sheet

- main/SS/Util/CellUtil.cs
Adding call to `CloneStyleFrom(originalStyle)` after creating the style when not found, and before overriding the style properties on `CellUtil.SetCellStyleProperties`. 
This is to avoid losing any other custom style properties set, i.e. FillForegroundXSSFColor
> Adding CloneStyleFrom to avoid losing custom style properties 

- OpenXmlFormats/Drawing/Chart/Chart.cs
- OpenXmlFormats/Drawing/SpreadsheetDrawing.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheDefinition.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheRecords.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotTableDefinition.cs
- OpenXmlFormats/Spreadsheet/Sheet.cs
- OpenXmlFormats/Vml/SpreadsheetDrawing.cs
- openxml4Net/Util/XmlHelper.cs
The main problem, the solution of which was the purpose of these changes, is to fill excel files with complex graphs and pivot tables using npoi, i.e. using such files as templates. I tested these changes on a relatively large file with several pivot charts, including slicers. I have not checked the creation of the Pivot tables and charts themselves in npoi, although I think it is possible.
Also please pay attention to `CT_AlternateContent` in [[OpenXmlFormats/Vml/SpreadsheetDrawing.cs](https://github.com/KnyazSh/npoi/blob/b261afeb6340174bcb3dbd134c5856b1519f8ad8/OpenXmlFormats/Vml/SpreadsheetDrawing.cs).](url) I had errors when using `innerXml` and had to use `outerXml`. I assume that something is lost by using wrapped innerXml.
> Add minimal support Pivot tables, Fix #419, Fix #262

- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheDefinition.cs
Hi @tonyqus.
I'm sorry I've been gone so long. I don't see the point in writing an explanation. But I will try to at least close this issue. I analyzed the request from @solarding and found another inconsistency in the pivotCacheDefinition entry. I think that with this fix we can close this issue and solve the rest within the new Issue. And so the fix turned out to be very big.
I will continue to try to improve your project, as this topic is close to me.
> Fix minValue and maxValue in SharedItems in CT_PivotCacheDefinition

- main/NPOI.Core.csproj
- main/NPOI.csproj
- main/packages.config
- ooxml/packages.config
- openxml4Net/packages.config
- testcases/main/NPOI.TestCases.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.csproj
This is to address issues CVE-2021-32840, CVE-2021-32842 and CVE-2021-32841 found in SharpZipLib, which are fixed in v1.3.3.
> Address cves for sharp zip lib

- main/HSSF/UserModel/HSSFCell.cs
- main/NPOI.Core.csproj
- main/SS/UserModel/Cell.cs
- main/SS/UserModel/DateUtil.cs
- ooxml/NPOI.OOXML.Core.csproj
- ooxml/XSSF/Streaming/SXSSFCell.cs
- ooxml/XSSF/UserModel/XSSFCell.cs
This PR adds support for setting cells through a `DateOnly` value.
> Add DateOnly support.

- main/SS/UserModel/DateUtil.cs
If date is more than `31/12/9999`, it's not a valid Excel date
> Add max date check in `IsValidExcelDate`

- ooxml/XWPF/Usermodel/XWPFStyles.cs
I don't see a reason the actual list of styles can't be exposed publicly, but without understanding the library enough in depth, I think this is an easy way to expose the list without causing any changes to the functionality of this class.
> Expose out list of styles for use

- OpenXmlFormats/Spreadsheet/AutoFilter.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheDefinition.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheRecords.cs
- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotTableDefinition.cs
- OpenXmlFormats/Spreadsheet/Sheet.cs
- OpenXmlFormats/Spreadsheet/Workbook/CT_Workbook.cs
- ooxml/XSSF/Model/CommentsTable.cs
- openxml4Net/Util/XmlHelper.cs
- testcases/main/NPOI.TestCases.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.csproj
- testcases/openxml4net/NPOI.OOXML4Net.Testcases.csproj
Completed CT_CustomFilters and CT_CustomFilter classes and their usage in AutoFilter
Added namespaces to pivot tables definition: xmlns:mc, mc:Ignorable, xmlns:xr. Changed some nodes serialization in pivot table parts, to conform with ECMA standard XSD of OOXML. 
Added reload for XmlHelper.WriteAttribute for string type values, that can accept a default value, to decide if this attribute should be present in stream or it can be omitted.
Pivot area property was serializing wrong, omitting "field" property when it has value of 0, which causes excel to repair the pivot tables that contain this object.
> Pivot tables serialization fixes

- main/SS/Formula/Functions/Match.cs
BUG：when match_type=1 and matching number, cannot be matched if the range contains empty cell。
> add null check in match function

- ooxml/XSSF/UserModel/XSSFSheetConditionalFormatting.cs
Limit of 3 rules does not exist anymore since Office 2007.
> Remove limit of 3 conditional formatting rules

- main/HSSF/UserModel/HSSFSheet.cs
- main/SS/UserModel/Sheet.cs
- main/SS/Util/SheetUtil.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- testcases/main/HSSF/UserModel/TestHSSFSheet.cs
- testcases/main/SS/Util/TestSheetUtil.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
There was AutoSizeColumn method, that adjusts width of the column to fit it's contents, but no such method to adjust the height of the row. This change implements such a method in a very similar to AutoSizeColumn way. It also adds a tests for new methods.
> Implement AutoSizeRow method

- OpenXmlFormats/Spreadsheet/Styles/CT_Font.cs
- ooxml/XSSF/UserModel/XSSFFontFormatting.cs
XSSFFontFormatting.FontColor setter used to set a new color to the CT_Font.colorField list which was not always initialized. This adds a method which first will check if the list is initialized and then adds a color to it. XSSFFontFormatting.FontColor setter now uses this method to set a color.
> Add AddColor method to CT_Font

- OpenXmlFormats/Drawing/Chart/Chart.cs
With resent change the parenthesis were broken. This fixes the problem.
> Fix ')' missing in CT_NumVal.Write method

- openxml4Net/OPC/PackageRelationship.cs
- testcases/openxml4net/OPC/TestPackageRelationship.cs
The source can be null. I was stuck by the exception when I want to copy a table row.
To fix the problem, I add a null-condition when getting the hashcode of source.And anohter  null-coalescing operator to return 0 when the hashcode result is null.
``` C#
public override int GetHashCode()
{
return this.id.GetHashCode() + this.relationshipType.GetHashCode()
+ this.source?.GetHashCode() ?? 0 + this.targetMode.GetHashCode()
+ this.targetUri.GetHashCode();
}
```
> Fix PackageRelationship.GetHashCode Exception because the source can be null

- OpenXmlFormats/Drawing/Chart/Chart.cs
- main/SS/Util/SheetUtil.cs
SixLabors.TextMeasurer measures strings differently than System.Common.Drawing did. The corrective coefficients here are not 100% accurate either, but they make sure, that cell contents are not cut off. The coefficient's values were tweaked by testing them on sizable sample of test strings with different fonts, font sizes and string lengths (and heights in case of multi-line strings). Accuracy will vary depending on font size and font itself, but on average accuracy is improved for most cases.
Fix incorrect number of rows count in merged region returned by GetNumberOfRowsInMergedRegion method:
Due to copy-paste it was actually returning a number of columns.
> Add correction to row height and column width obtained in SheetUtil methods

- ooxml/XSSF/UserModel/XSSFRow.cs
Code clean-up, refactor into more of C# style code, use expression body style for properties and methods where applicable, use 'var' instead of explicit types where possible, add curly brackets for clarity in places where they were omitted, re-arrange members into regions.
Change javadoc to c# xml documentation.
No changes in code itself or logic, only refactoring.
> Refactoring XSSFRow

- main/SS/Util/Format.cs
- testcases/main/NPOI.TestCases.csproj
- testcases/main/SS/Util/TestSimpleDateFormat.cs
Fixed the issue as portrayed in #846. Also added a basic test regarding `SimpleDateFormat.Parse`.
This fix is done by adding a compatibility stub into the aforementioned method allowing a leading space before one-digit hour instead of the regular zero.
Since the new approach utilizes `DateTime.ParseExact`, the change won't enable other ill-formed datetime strings.
> Able to open files with ill-formed datetime, exported by SAS

- OpenXmlFormats/Drawing/Chart/Chart.cs
- ooxml/XSSF/UserModel/Charts/XSSFChartUtil.cs
- openxml4Net/OPC/PackagePartName.cs
- openxml4Net/OPC/PackagingUriHelper.cs
- testcases/openxml4net/TestPackagingURIHelper.cs
This reverts previous incorrect #930 fix.
I have reproduced and tested #930 fix with .net core 6.0 version as follows:
I have used LineChart.cs example with 277 different locales and all files open fine on my italian Excel version. 
The generated files are attached.
During this process I found a bug with locale th-TH which I fixed under #944 
The ru-ru culture bug found, under #376 is also checked and fixed.
[testlinechart-locales.zip](https://github.com/nissl-lab/npoi/files/9893406/testlinechart-locales.zip)
> Fixes internationalization bugs #930 #944 #376

- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
fixes #583 by setting `zos.UseZip64 = UseZip64.Off` in `SXSSFWorkbook.InjectData`. This generates a zip file with header `04 03 4b 50 14`, which can be opened also in Google Drive and LibreOffice.
> Create zip for SXSSFWorkbook setting Use64bit=Off

- ooxml/XSSF/UserModel/XSSFDrawing.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFChart.cs
When new chart was created it's number was determined by the number of previously existing charts. This created a bug, when there were charts chart1.xml and chart2.xml, chart1 was deleted and the new chart was created. Since there is a chart already (chart2), the number for a new chart would be 2 (CountOfCharts + 1). This will throw an exception, because chart2.xml already exists.
Also added a RemoveChart method to XSSFDrawing and tests for the fixed bug and for the the RemoveChart method
> Fix delete and add chart throws exception

- main/HSSF/UserModel/HSSFWorkbook.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- testcases/main/SS/UserModel/BaseTestBugzillaIssues.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFBugs.cs
This PR fixes issue #931. In practice, I've encountered it too when I tried to change sheet order after setting PrintArea in each sheets.
Referenced POI source code version: POI 5.2.3
----
POI Bug Tracker issue:
https://bz.apache.org/bugzilla/show_bug.cgi?id=60197
Tracked POI changes:
- bug 60197: Workbook#setSheetOrder should update named range sheet indices 
https://svn.apache.org/repos/asf/poi/trunk@1763939
- sonar fixes - use assert in junit tests
https://svn.apache.org/repos/asf/poi/trunk@1872397
- #65026 - Migrate tests to Junit 5
https://svn.apache.org/repos/asf/poi/trunk@1884783
(comment: Actual logic fix was only in first revision, rests were test code adjustments.)
> fix POI Bug 60197 - setSheetOrder doesn't update names scope

- main/HPSF/MutableSection.cs
It was messing up getting a Size property of a MutableSection, as it reads the MutableProperty's Value and tries to get it's length, throwing a null reference exception.
> Stop MutableSection from setting null MutableProperty

- OpenXmlFormats/NPOI.OpenXmlFormats.csproj
- main/NPOI.Core.csproj
- main/NPOI.csproj
- ooxml/NPOI.OOXML.csproj
- openxml4Net/NPOI.OpenXml4Net.csproj
When I had tried to build NPOI.sln with VS2022, I always got `Ambiguous project name 'NPOI'` error while restoring NuGet packages. Therefore, I was able able to test only NPOI.Core build until recently.
After some search I found https://github.com/NuGet/Home/issues/7372 that says all csproj files should have unique or empty PackageId.
So I removed all `<PackageId>NPOI</PackageId>` settings from csproj files to resolve the ambiguous project name error.
> fix `Ambiguous project name` error while restoring NuGet packages.

- main/SS/Formula/Functions/DateValue.cs
- main/SS/Formula/Functions/Indirect.cs
- ooxml/POIXMLDocumentPart.cs
A couple of leftover files I missed in PR #1034.
> Remove unused exception captures

- Directory.Build.props
- OpenXmlFormats/NPOI.OpenXmlFormats.Core.csproj
- main/NPOI.Core.csproj
- ooxml/NPOI.OOXML.Core.csproj
- openxml4Net/NPOI.OpenXml4Net.Core.csproj
- testcases/main/NPOI.TestCases.Core.csproj
- testcases/main/NPOI.TestCases.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.csproj
- testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
- testcases/openxml4net/NPOI.OOXML4Net.Testcases.csproj
Next of #1031.
1. Make tests runnable for .NET Framework v4.7.2 with VS2022
In `NPOI.Test.sln` I got internal errors during test case search with the combination of  VS2022 + NUnit3TestAdapter 4.2.1, then I cannot execute any test cases those are listed in Test Explorer.
To fix the error, update NUnit3TestAdapter version to 4.3.1 .
In `NPOI.Core.Test.sln`, the problem didn't happen, but I also update NUnit3TestAdapter for consistency.
1. Update NuGet packages versions for consistency between Core and Framework csprojs
Microsoft.SourceLink.GitHub  --> 1.1.1  (in `Directory.Build.props`)
NSubstitute  --> 4.2.2
NUnit  --> 3.13.3
> Build process maintenance 3rd

- OpenXmlFormats/Wordprocessing/Table.cs
- ooxml/XWPF/Usermodel/XWPFTable.cs
- testcases/ooxml/XWPF/UserModel/TestXWPFTable.cs
Fix XWPFTable row cannot insert to the last position of table.
The problem is in CT_Tbl.GetItems1Index method.
Because pos can never be equal to p in for loop, I add a statement to check if the index is -1 and ``` pos == p ``` after for loop. It means that the position is the end of the list. 
``` C#
for (int i = 0; i < items1ElementNameField.Count; i++)
{
if (items1ElementNameField[i] == type)
{
if (pos == p)
{
//return itemsField[p] as T;
index = i;
break;
}
else
pos++;
}
}
// Check if the position should be the last position
if(index == -1 && pos == p) 
index = items1Field.Count;
```
> Fix XWPFTable row cannot insert to the last position of table

- OpenXmlFormats/Drawing/BaseTypes.cs
- OpenXmlFormats/Drawing/Chart/AreaChart.cs
- OpenXmlFormats/Drawing/Chart/Chart.cs
- OpenXmlFormats/Drawing/Chart/PieChart.cs
- main/NPOI.csproj
- main/SS/UserModel/Charts/AreaChartData.cs
- main/SS/UserModel/Charts/AreaChartSeries.cs
- main/SS/UserModel/Charts/BarChartData.cs
- main/SS/UserModel/Charts/BarChartSeries.cs
- main/SS/UserModel/Charts/ChartDataFactory.cs
- main/SS/UserModel/Charts/ColumnChartData.cs
- main/SS/UserModel/Charts/ColumnChartSeries.cs
- main/SS/UserModel/Charts/PieChartData.cs
- main/SS/UserModel/Charts/PieChartSeries.cs
- main/SS/UserModel/Charts/ScatterChartData.cs
- ooxml/NPOI.OOXML.csproj
- ooxml/XSSF/UserModel/Charts/XSSFAreaChartData.cs
- ooxml/XSSF/UserModel/Charts/XSSFBarChartData.cs
- ooxml/XSSF/UserModel/Charts/XSSFChartDataFactory.cs
- ooxml/XSSF/UserModel/Charts/XSSFColumnChartData.cs
- ooxml/XSSF/UserModel/Charts/XSSFPieChartData.cs
- ooxml/XSSF/UserModel/Charts/XSSFScatterChartData.cs
- ooxml/XSSF/UserModel/XSSFChart.cs
Add implementation for Area, Pie and partly a Column chart types, minor fixes for charts. 
Column chart still needs the _AddNewColumnChart_ implemented in _OpenXmlFormats/Drawing/Chart/Chart.cs_
Part of the implementation for #581
> Implement Area and Pie chart types

- main/HSSF/Model/RecordOrderer.cs
> Skip WINDOW2 validation when reading possibly non-compliant XLS

- OpenXmlFormats/Spreadsheet/Sheet/CT_Col.cs
- OpenXmlFormats/Spreadsheet/Sheet/CT_Cols.cs
- OpenXmlFormats/Spreadsheet/Sheet/CT_Comment.cs
- OpenXmlFormats/Vml/Main.cs
- main/HSSF/UserModel/HSSFSheet.cs
- main/SS/Formula/FormulaShifter.cs
- main/SS/UserModel/Helpers/RowShifter.cs
- main/SS/UserModel/Sheet.cs
- main/SS/Util/CellUtil.cs
- main/SS/Util/SheetUtil.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/UserModel/Helpers/ColumnHelper.cs
- ooxml/XSSF/UserModel/Helpers/XSSFRowColShifter.cs
- ooxml/XSSF/UserModel/XSSFCell.cs
- ooxml/XSSF/UserModel/XSSFRow.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- testcases/main/HSSF/UserModel/TestHSSFSheet.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
This PR aims to mainly cleanup and make more consistent and readable the code of XSSFSheet class,
but touching some adjacent classes, such as XSSFRowColShifter, RowShifter and ColumnHelper. 
The core reason for this change to exist is to be a platform to later build functionality to manage columns of the sheet
the same way rows are managed, with column shifting etc. Hopefully this improves maintainability and stability somewhat. It is easier to track changes of XSSFSheet, XSSFRowColShifter, RowShifter and ColumnHelper classes in the commit history, since there's a lot of moving stuff around and diffs don't do a good job representing the picture of what happened. Public API has no breaking changes, no new failed tests are generated.
Among the changes:
* Converts javadoc to csharp xml …
> Refactoring and code cleanup for XSSFSheet, XSSFRowColShifter, RowShifter and ColumnHelper classes

- OpenXmlFormats/Drawing/Chart/Chart.cs
This caused files to be broken when they were saved with special xml symbols in the charts axis names.
> Fix bug with cashed chart axis name not being XMLEncoded on save

- ooxml/XSSF/UserModel/XSSFVMLDrawing.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFVMLDrawing.cs
- testcases/test-data/spreadsheet/vmlDrawing1.vml
XSSFVMLDrawing.Read method would remove the opening br tag, and normally it will be enough, because normally a br tag doesn't need closing tag. But sometimes it has one, so it needs to be removed also.
The pull request also adds a test for the issue.
> Fix exception thrown when reading file with closing </br> tag in drawing.vml

- main/HSSF/UserModel/StaticFontMetrics.cs
- main/SS/Formula/Function/FunctionMetadataReader.cs
- ooxml/XSSF/UserModel/XSSFBuiltinTableStyle.cs
There are three embedded resouces in NPOI.
- `functionMetadata.txt` and `font_metrics.properties` in NPOI project
- `presetTableStyles.xml` in NPOI.OOXML project
In previous, thee resource files on net472 has inconsistent settings against NET Core.
- NPOI.csproj:
The two files had shorthand `LogicalName`s.
```
<ItemGroup>
<EmbeddedResource Include="Resources\functionMetadata.txt">
<LogicalName>functionMetadata.txt</LogicalName>
</EmbeddedResource>
<EmbeddedResource Include="Resources\font_metrics.properties">
<LogicalName>font_metrics.properties</LogicalName>
</EmbeddedResource>
</ItemGroup>
```
- NPOI.OOXML.csproj:
`presetTableStyles.xml` had been properly regeistered in NPOI.OOXML.Core.csproj, but not in NPOI.OOXML.csproj as EmbeddedResource, so it had been already broken in net472. …
> fix EmbeddedResource access on net472

- main/SS/Formula/FormulaCellCacheEntry.cs
Using a HashSet to reduce the time complexity of the `ChangeConsumingCells` method.
Similar to what is done in the original POI implementation:
https://github.com/apache/poi/blob/43b0529a67c813ae1ebd0812a7c8d87332704d71/poi/src/main/java/org/apache/poi/ss/formula/FormulaCellCacheEntry.java#L93
This change greatly improves the performance of formula value caching when the worksheet contains a lot of cells.
> FormulaCellCacheEntry: Optimize ChangeConsumingCells method

- .github/workflows/PR.yml
- .nuke/build.schema.json
- build.ps1
- build.sh
- build/Build.GitHubAction.cs
- build/Build.cs
- build/_build.csproj
- solution/NPOI.Core.Test.sln
- testcases/main/NPOI.TestCases.Core.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
- testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
* NUKE 7.0.2
* don't print missing documentation warnings
* don't build NUKE project as part of solution
* use also Ubuntu for building (faster builds)
* skip tests as Appveyour isn't testing either
* separate workflow for PRs (still same for master build)
NUKE update was done using the latest global tool and running command `nuke :update`. New GitHub workflow files were generated by running `build.cmd`, NUKE updated definitions automatically. Maybe at some point could also enable tests when they are green in master 😉
> NUKE improvements

- .gitignore
- Directory.Build.props
- benchmarks/NPOI.Benchmarks/LargeExcelFileBenchmark.cs
- benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
- benchmarks/NPOI.Benchmarks/Program.cs
- benchmarks/NPOI.Benchmarks/RangeValuesBenchmark.cs
- solution/NPOI.Core.Test.sln
This PR adds a new benchmark project which utilizes [BenchmarkDotNet](https://benchmarkdotnet.org/) for precise and repeatable results. I adjusted test cases from [this blog post](https://www.grapecity.com/blogs/npoi-apache-poi-alternative-gcexcel-net ) to create presentation of areas.
I have diff tools that I can use to show performance changes between master and proposed optimization.
You can run the benchmarks by simply running the benchmarks project using `Release` configuration. It will as what benchmark(s) to run.
My first PR will tackle the `LargeExcelFileBenchmark.Evaluate` which is obviously the worst case at the moment as it takes over a minute to complete on my desktop.
``` ini
BenchmarkDotNet=v0.13.5, OS=Windows 11 (10.0.23466.1001)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 …
```
> Add benchmarks project

- OpenXmlFormats/Spreadsheet/Styles/CT_Xf.cs
- ooxml/XSSF/Model/StylesTable.cs
- ooxml/XSSF/UserModel/XSSFCellStyle.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFCellStyle.cs
Fix Issue #1025
XSSFCellStyle.CloneStyleFrom was breaking styles in SXSSFWorkbook because it was creating a new _cellXf while XSSFCellStyle.Index was old and referred to the old _cellXf.
> Fix XSSFCellStyle.CloneStyleFrom

- main/HSSF/Record/SSTDeserializer.cs
- testcases/main/HSSF/Record/TestSSTDeserializer.cs
- testcases/test-data/spreadsheet/notenoughstrings.txt
Fixing a problem when the shared string table record reports more strings than are present in the file.
This is based on the same fix/patch for POI Java, see link => https://bz.apache.org/bugzilla/show_bug.cgi?id=66412 Credit to simon.carter for this fix.
The current behaviour is: read the number of strings in the string table. Then attempt to read that many number of strings. Using subsequent records if needed. If there are less strings present than reported, pad the internal string table with empty strings. This only works when there are no more records in the stream.
This fix adds a check to ensure that the next record is a continuation record. If it is not then the internal string table is padded as before.
> POI 65543 Bug Fix Sync

- Directory.Build.props
- build/Build.cs
- main/NPOI.Core.csproj
- ooxml/NPOI.OOXML.Core.csproj
- openxml4Net/NPOI.OpenXml4Net.Core.csproj
- solution/NPOI.Core.Test.sln
- solution/NPOI.Pack.csproj
- testcases/Directory.Build.props
- testcases/main/NPOI.TestCases.Core.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
- testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
Adding a separate `NPOI.Pack.csproj` project that references other projects and thus creates a NuGet package that has all dependencies inside. This changes `NPOI.dll` to be `NPOI.Core.dll` (like the project actually is) in order for pack to succeed. Uses Nugetizer reference which fixes project references to be also part of NuGet package contents.
Ideally there would be separate NuGet packages for each on NuGet or as now there's build output (dll and pdb) for each dependency multiple times in package output. The package size is now 11MB which is quite big but that's the way to roll I guess with current setup where Core is/was packaging target and reverse-dependencies are needed.
With Nugetizer there's no snupkg anymore sore pdbs are part of the main NuGet package.
> Include all projects in NuGet package

- main/SS/Formula/Functions/Int.cs
This closes #983 
Since in excel INT function definition is "Rounds a number down to the nearest integer", change the function from Math.Round to Math.Floor
> fix issue #983 INT(1.99) doesn't return correct rounded value

- main/SS/Formula/Functions/Baseifs.cs
- main/SS/Formula/Functions/Countifs.cs
- testcases/main/SS/Formula/Functions/CountifsTests.cs
1. This closes #825  (porting Baseifs from POI)
2. add Countifs test case to track multi rows scenario
> Countifs fail to evaluate correctly #825

- main/SS/Formula/Eval/TwoOperandNumeric/MultiplyEval.cs
- solution/NPOI.Core.Test.sln
- testcases/main/SS/Formula/Eval/TestMultiplyEval.cs
- testcases/main/SS/Formula/PTG/TestExternalNameReference.cs
this closes #1055 
1. use decimal to replace double on precision issue
2. add a unit test file to track the issue
> fix #1055 Unexpected ROUNDDOWN function Result

- ooxml/XWPF/Usermodel/XWPFDocument.cs
Thanks so much for this library! I just replaced an internal tool's usage of the office interop with this and it's been a great experience overall. I stumbled upon a small bug within `FindAndReplaceText` when there are nested tables.
> Support replacing docx text within embedded tables

- OpenXmlFormats/CustomXmlSchemaProperties.cs
- OpenXmlFormats/Drawing/WordprocessingDrawing.cs
- OpenXmlFormats/Spreadsheet/Document/CalcChainDocument.cs
- OpenXmlFormats/Spreadsheet/Sheet.cs
- OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
- OpenXmlFormats/Spreadsheet/Sheet/CT_Row.cs
- OpenXmlFormats/StreamWriterExtensions.cs
- OpenXmlFormats/Vml/WordprocessingDrawing.cs
- OpenXmlFormats/Wordprocessing/BaseTypes.cs
- OpenXmlFormats/Wordprocessing/CustomXml.cs
- OpenXmlFormats/Wordprocessing/Document.cs
- OpenXmlFormats/Wordprocessing/FormField.cs
- OpenXmlFormats/Wordprocessing/Frame.cs
- OpenXmlFormats/Wordprocessing/HdrFtr.cs
- OpenXmlFormats/Wordprocessing/Markup.cs
- OpenXmlFormats/Wordprocessing/Numbering.cs
- OpenXmlFormats/Wordprocessing/PageSetup.cs
- OpenXmlFormats/Wordprocessing/Paragraph.cs
- OpenXmlFormats/Wordprocessing/Picture.cs
- OpenXmlFormats/Wordprocessing/RangePermission.cs
- OpenXmlFormats/Wordprocessing/Run.cs
- OpenXmlFormats/Wordprocessing/Sdt.cs
- OpenXmlFormats/Wordprocessing/Settings.cs
- OpenXmlFormats/Wordprocessing/Styles.cs
- OpenXmlFormats/Wordprocessing/Tab.cs
- OpenXmlFormats/Wordprocessing/Table.cs
- OpenXmlFormats/Wordprocessing/wml.cs
- openxml4Net/Util/XmlHelper.cs
`string.Format` is a bad thing in hot paths. Changed code to call multiple `Write`s instead of string concatenation.
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |Load|11.741 s|1.1257 s|3.65 GB|
| **New** |	| **11.626 s (-1%)** | **2.0913 s** | **3732.62 MB (0%)** |
| Old |Write|3.483 s|0.1738 s|1.19 GB|
| **New** |	| **3.058 s (-12%)** | **0.2296 s** | **611.83 MB (-50%)** |
| Old |Evaluate|62.677 s|4.1891 s|75.32 GB|
| **New** |	| **64.658 s (+3%)** | **24.1520 s** | **77128.7 MB (0%)** |
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |Double|85.46 ms|0.367 ms|31.45 MB|
| **New** |	| **82.83 ms (-3%)** | **0.382 ms** | **26.98 MB (-14%)** |
| Old |String|99.93 ms|0.449 ms|59.32 MB|
| **New** |	| …
> Reduce string allocations when writing documents

- OpenXmlFormats/Drawing/Chart/Chart.cs
- main/HSSF/UserModel/HSSFCell.cs
- main/SS/Format/CellFormat.cs
- main/SS/UserModel/Cell.cs
- main/SS/UserModel/DataFormatter.cs
- ooxml/XSSF/Streaming/SXSSFCell.cs
- ooxml/XSSF/UserModel/XSSFCell.cs
- testcases/main/HSSF/UserModel/TestHSSFCell.cs
- testcases/main/HSSF/UserModel/TestHSSFDateUtil.cs
- testcases/main/SS/UserModel/BaseTestCell.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
- Change DateTimeCellValue from type DateTime to DateTime?
- Change behavior of getting DateTime cell value - return null if the cell type is not numeric or formula 
- Add DateOnlyCellValue property to ICell
- Add TimeOnlyCellValue property to ICell
> Add DateOnlyCellValue and TimeOnlyCellValue

- main/SS/Formula/Functions/Text/Text.cs
- testcases/main/SS/Formula/Functions/TestText.cs
In excel, this text function can also be used with strings (not only numeric values)
> Update Text.cs to handle StringEval in arg0

- ooxml/XSSF/Streaming/SXSSFCell.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFComment.cs
This PR fixies POI bug with removing comments in SXSSF
> Fix removing cell comments in SXSSF

- main/SS/Formula/Functions/Text/SearchFind.cs
Update SearchFind.cs to not throw an unhandled exception when startIndex is >= to length of string to search in
> Update SearchFind.cs to not throw an unhandled exception 

- main/SS/Formula/Functions/EDate.cs
- main/Util/StringUtil.cs
- openxml4Net/OPC/Internal/PackagePropertiesPart.cs
RT
looks like incorrect porting from Java to C# / from Hashtable to Dictionary.
> Fix warnings on comparing value types to null

- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
> Fix Remove method of XSSFWorkbook

- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
- testcases/ooxml/XSSF/Streaming/SXSSFWorkbookTests.cs
> Fix leaveOpen option of SXSSFWorkbook

- .github/workflows/CI.yml
- .github/workflows/PR.yml
- build/Build.GitHubAction.cs
- build/Build.cs
- testcases/ooxml/XSSF/Streaming/TestAutoSizeColumnTracker.cs
Now using proper (twice the size) version of Noto Emoji font that has proper tables that SixLabors.Fonts expects. Also removed caching step as most of the dependencies are already installed and I/O is expensive on VM hosts.
> Fix Linux font installation with proper NotoColorEmoji-Regular.ttf 

- main/HSSF/Util/HSSFColor.cs
Remove reflections to retrieve the 2nd index, by adding a virtual getter.
> Remove reflections in `HSSFColor`

- ooxml/XSSF/UserModel/XSSFSheet.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
The method wasn't removing the hyperlinks from CT_Hyperlinks array, only from a list in the hyperlinks property. Now it removes the hyperlink in both places.
Related to #1128
Updated the test for #690 to make sure the correct link is removed by the method.
> Fix XSSFSheet.RemoveHyperlink method.

- .github/workflows/CI.yml
- .github/workflows/PR.yml
- build/Build.GitHubAction.cs
- build/Build.cs
* include `release*` branches
* read version from branch name if starts with `release`
* change output from artifacts to publish (artifacts will be used by NET 8 for binaries)
As i used `release1.5.1` (an imaginary version) as my branch name, you can see that the build on my fork determined this to be publish build and forced all version information from the branch name, output from ubuntu-latest run:
```
06:13:26 [INF] BUILD SETUP
06:13:26 [INF] 	Solution: /home/runner/work/npoi/npoi/solution/NPOI.Core.Test.sln
06:13:26 [INF] 	Configuration: Release
06:13:26 [INF] 	Version suffix: 
06:13:26 [INF] 	Publish version: 1.5.1
06:13:26 [INF] Build environment:
06:13:26 [INF] 	Host: Nuke.Common.CI.GitHubActions.GitHubActions
```` 
The summary has the Artifacts at the bottom …
> Improve package publish logic

- main/SS/Util/SheetUtil.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFBugs.cs
> Fix copying empty row

- benchmarks/NPOI.Benchmarks/AutoSizeColumnBenchmark.cs
- main/SS/Util/SheetUtil.cs
Adding caching to font creation as it can be quite costly. Showing the difference it makes by creating benchmark for `AutoSizeColumn`.
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |AutoSizeColumn|1.329 s|0.0156 s|673.13 MB|
| **New** |	| **144.3 ms (-89%)** | **1.94 ms** | **130.58 MB (-81%)** |
> Add caching to IFont2Font

- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
This PR fixes #1182
Because RepeatingRows and RepeatingColumns are part of the Workbook, they're not serialized during creating a copy of the sheet. Just copy them manually
> Copy RepeatingRows and RepeatingColumns

- OpenXmlFormats/Spreadsheet/Sheet.cs
- main/HSSF/Model/InternalSheet.cs
- main/HSSF/Record/Aggregates/ColumnInfoRecordsAggregate.cs
- main/HSSF/UserModel/HSSFSheet.cs
- main/SS/UserModel/Sheet.cs
- ooxml/SS/Converter/ExcelToHtmlConverter.cs
- ooxml/SS/Converter/ExcelToHtmlUtils.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFDialogsheet.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- openxml4Net/Util/XmlHelper.cs
- testcases/main/HSSF/UserModel/TestHSSFSheet.cs
- testcases/main/SS/UserModel/BaseTestBugzillaIssues.cs
- testcases/main/SS/UserModel/BaseTestSheetAutosizeColumn.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFSheetAutoSizeColumn.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
This PR fixes DefaultColumnWidth type and implementation. Due to POI bug it returned baseColumnWidth, which is integer. This is a breaking change.
Fixes #943
> Fix DefaultColumnWidth

- main/DDF/DefaultEscherRecordFactory.cs
- main/HSSF/Record/CFHeader12Record.cs
- main/HSSF/Record/CFHeaderRecord.cs
- main/HSSF/Record/CFRule12Record.cs
- main/HSSF/Record/CFRuleRecord.cs
- main/HSSF/Record/Chart/LinkedDataRecord.cs
- main/HSSF/Record/Chart/StartBlockRecord.cs
- main/HSSF/Record/RecordFactory.cs
RT. This PR converts reflection-based `CreateInstance` to a static dispatch table.
> Remove reflections in `DDF.EscherRecord` and `HSSF.Record`

- main/Util/CustomPOILoggerFactory.cs
- main/Util/POILogFactory.cs
The original impl doesn't look quite right. For example, `Type.GetType` requires `FullName` but fed with `Name`. Nevertheless, a custom factory class is now required to eliminate reflections.
This will be a breaking change if the user uses custom logger.
> Remove reflections in POI Logger

- main/HSSF/UserModel/OperationEvaluatorFactory.cs
- main/POIFS/NIO/FileBackedDataSource.cs
- main/SS/Formula/Eval/Forked/ForkedEvaluator.cs
- openxml4Net/Util/ZipSecureFile.cs
These 4 classes use reflection codes but don't work due to various reasons (such as wrong porting from Java to NET).
Besides they are not used elsewhere in NPOI.
> Remove reflections in unused (or not working) classes

- main/SS/Util/SheetUtil.cs
Small speedup on autosizing column width
> Small speedup on autosizing column width

- ooxml/Util/DocumentPartCreationHelper.cs
- ooxml/XSSF/UserModel/DocumentPartCreationHelper.cs
- ooxml/XSSF/UserModel/XSSFChart.cs
- ooxml/XSSF/UserModel/XSSFChartSheet.cs
- ooxml/XSSF/UserModel/XSSFFactory.cs
- ooxml/XSSF/UserModel/XSSFPivotCache.cs
- ooxml/XSSF/UserModel/XSSFPivotCacheDefinition.cs
- ooxml/XSSF/UserModel/XSSFPivotCacheRecords.cs
- ooxml/XSSF/UserModel/XSSFPivotTable.cs
- ooxml/XSSF/UserModel/XSSFVMLDrawing.cs
- ooxml/XWPF/Usermodel/XWPFFactory.cs
- ooxml/XWPF/Usermodel/XWPFPictureData.cs
Convert `POIXMLFactory.CreateDocumentPart` into a static dispatch to enable AOT. 
It's the first problem when Nuget NPOI is compiled with AOT.
> Remove reflections in `POIXMLFactory.CreateDocumentPart`

- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
This PR is connected to #958. That fix solved the compatibility issue. However, `SXSSFWorkbook` is now unable to produce working files when adding sheets larger than 4 GB.
> Make it possible to set UseZip64 flag

- ooxml/NPOI.OOXML.Core.csproj
This is a fix to update the transitive reference of `System.Security.Cryptography.Pkcs` to `6.0.3` to mitigate [CVE-2023-29331](https://github.com/dotnet/announcements/issues/257). By default, the version pulled in is `6.0.1` which contains this vulnerability and causes Aqua Trivy to scan the `*.deps.json` and raise this error.
> Update transitive reference to Cryptography.Pkcs library

- main/NPOI.Core.csproj
https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/releases/tag/3.0.0
If you have a solution that references the latest 3.0.0 version NPOI will throw an error:
> NPOI.Util.RecordFormatException : Unable to construct record instance
----> System.MissingMethodException : Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream(Byte[])'.
Stack Trace:
at NPOI.HSSF.Record.RecordFactory.ReflectionConstructorRecordCreator.Create(RecordInputStream in1)
at NPOI.HSSF.Record.RecordFactory.CreateSingleRecord(RecordInputStream in1)
at NPOI.HSSF.Record.RecordFactoryInputStream.ReadNextRecord()
at NPOI.HSSF.Record.RecordFactoryInputStream.NextRecord()
at NPOI.HSSF.Record.RecordFactory.CreateRecords(Stream in1)
at …
> Upgrade Microsoft.IO.RecyclableMemoryStream to version 3.0.0

- main/NPOI.Core.csproj
Update SixLabors dependencies to address ImageSharp DDOS security issue
> Update SixLabors dependencies

- main/NPOI.Core.csproj
Update SixLabors.ImageSharp to address CVE-2024-27929
> Update SixLabors.ImageSharp (CVE-2024-27929)

- OpenXmlFormats/Spreadsheet/Sheet.cs
`CT_CellFormula.Write` method ensure the `siField` is written into `fField`'s attributes on `Write` even when it has a default value for cases when the type of the formula is shared formula.
It seems that Excel expects this atribute to be written into xml even when it is of the default value for shared formulas. If not present - the xlsx file is flagged by it as broken and is repaired.
Not test is added because it is hard to test for Excel not trying to repair the file.
> CT_CellFormula.Write: fix writing the si attribute

- main/NPOI.Core.csproj
Update SixLabors.ImageSharp to 2.1.8 to address [CVE-2024-32036](https://nvd.nist.gov/vuln/detail/CVE-2024-32036)
> Update SixLabors.ImageSharp to 2.1.8. CVE-2024-32036

- OpenXmlFormats/Spreadsheet/Sheet.cs
- main/HSSF/Record/Aggregates/DataValidityTable.cs
- main/HSSF/Record/DVRecord.cs
- main/HSSF/UserModel/HSSFSheet.cs
- main/SS/UserModel/Sheet.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- testcases/main/HSSF/UserModel/TestDataValidation.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFDataValidation.cs
This PR adds a `RemoveDataValidation` to the `ISheet` implementations to allow the removal of a data validation rule.
> Add RemoveDataValidation method

- main/SS/Formula/Eval/OperandResolver.cs
- main/SS/Formula/Eval/StringEval.cs
- main/SS/Formula/Functions/Text/Exact.cs
- main/SS/Formula/Functions/Text/Text.cs
- main/SS/Formula/Functions/Text/TextFunction.cs
- main/SS/UserModel/DataFormatter.cs
- testcases/main/SS/Formula/Functions/TestText.cs
Bugzilla URL: https://bz.apache.org/bugzilla/show_bug.cgi?id=67475
SVN revision: https://svn.apache.org/viewvc?view=revision&revision=1912973
This also fixes parsing of doubles in DataFormatter as it will now pass current culture object to double.Parse() method.
> [POI-Bug-67475] Better support for edge cases in TEXT function.

- main/SS/Formula/Eval/OperandResolver.cs
- main/SS/Formula/Eval/StringEval.cs
- main/SS/Formula/Functions/Text/Exact.cs
- main/SS/Formula/Functions/Text/Text.cs
- main/SS/Formula/Functions/Text/TextFunction.cs
- main/SS/UserModel/DataFormatter.cs
- testcases/main/SS/Formula/Functions/TestText.cs
> Revert "[POI-Bug-67475] Better support for edge cases in TEXT function."

- openxml4Net/OPC/PackageRelationshipCollection.cs
sync code from https://github.com/apache/poi/commit/cdb2ba13989badf60d88c75daf69c94ae6ac2e13
fix #1229
> Fix NPE issue in PackageRelationshipCollection

- OpenXmlFormats/Spreadsheet/Styles/CT_CellStyleXfs.cs
- OpenXmlFormats/Spreadsheet/Styles/CT_Xf.cs
This fix removes the `xfId` attribute from `xf` elements in the `cellStyleXfs` collection.
When writing the `styles.xml` file NPOI includes a `xfId` attribute in the `xf` elements of the cell style format collection
```xml
<cellStyleXfs count="1">
<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
</cellStyleXfs>
```
The `xfId` attribute is meaningless in `cellStyleXfs` collections.  The `xf` record is also used in the `cellXfs` collection where `xfId` is an index into `cellStyleXfs`.
If you load a generated file into Excel and save it the `xfId` is stripped out of `cellStyleXfs` elements.
Unfortunately, inclusion of the `xfId` attribute in the `cellStyleXfs` collection can cause other applications to fail.  [Spotfire](spotfire.com) will not read a file created with NPOI. …
> Do not include xfId in CellStyleXfs XML

- ooxml/XSSF/Streaming/SheetDataWriter.cs
- testcases/ooxml/XSSF/Streaming/SheetDataWriterTests.cs
Bugzilla url: https://bz.apache.org/bugzilla/show_bug.cgi?id=68237
SVN revision: https://svn.apache.org/viewvc?view=revision&revision=1914152
> [Bug 68237] CustomHeight attribute of row for SXSSFWorkbook is wrong 

- main/SS/Formula/Eval/FunctionEval.cs
- main/SS/Formula/Functions/Cell.cs
- testcases/main/SS/Formula/Functions/TestRowCol.cs
https://support.microsoft.com/en-us/office/cell-function-51bd39a5-f338-4dbe-a33f-955d67c2b2cf
This implementation is not complete. It only implements 'row' and 'col'. 
We will implement the rest if feature feature request is created. 
This PR fixes #817
> Implement Cell function

- main/SS/Formula/Atp/AnalysisToolPak.cs
- main/SS/Formula/Functions/Text/Concat.cs
- main/SS/Formula/Functions/Text/TextFunction.cs
- testcases/main/SS/Formula/Atp/TestConcat.cs
Fix #1088, Implement CONCAT function , add Some Tests
>  Implement Concat Function

- ooxml/POIXMLDocument.cs
- ooxml/SS/UserModel/WorkbookFactory.cs
- ooxml/Util/PackageHelper.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- openxml4Net/OPC/OPCPackage.cs
> Expose Package Readonly argument for XSSFWorkbook constructor

- main/SS/Formula/Atp/AnalysisToolPak.cs
- main/SS/Formula/Functions/TInv.cs
- testcases/main/SS/Formula/Functions/TestTInv.cs
Fix #1273 , Implement T.INV Function and add TINV Tests
> Implement T.INV Function

- main/NPOI.Core.csproj
There's a security vulnerability in 2.3.0: https://github.com/advisories/GHSA-v435-xc8x-wvr9
> Upgrade BouncyCastle.Cryptography to version 2.3.1

- Directory.Build.props
- benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
- testcases/main/NPOI.TestCases.Core.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
- testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
Should be quite safe to upgrade if the build is green. None of these are shipped with the actual artifacts.
> Upgrade benchmark and test NuGet references

- Directory.Build.props
- OpenXmlFormats/Properties/AssemblyInfo.cs
- build/Build.GitHubAction.cs
- build/Build.cs
- main/Properties/AssemblyInfo.cs
- ooxml/Properties/AssemblyInfo.cs
- openxml4Net/Properties/AssemblyInfo.cs
Now `Directory.Build.props`'s version number in `<VersionPrefix>` is the single source of truth for the version (and other metadata) information. No need to copy paste and sync multiple files.
This is what the DLL metadata looks with local (Release) build:
fixes #1372
> Use Directory.Build.props as single source of version information

- Directory.Build.props
`RepositoryUrl` currently points to forked repository and I think it should point to this main repository.
> Fix RepositoryUrl in Directory.Build.props

- main/NPOI.Core.csproj
- main/Util/POILogFactory.cs
- main/Util/SystemOutLogger.cs
- testcases/main/NPOI.TestCases.Core.csproj
* the dependency brings legacy packages (DLLs) with it to modern .NET
* usages are for advanced cases and I'd argue rarely used
* keep the support on full framework where .config files still are a thing
* allow configuration via environment variables on non-framework platforms
> Remove System.Configuration.ConfigurationManager as NuGet dependency

- Directory.Packages.props
Enabling pinning which allows to define all target versions in `Directory.Packages.props`.  `dotnet restore --force-evaluate -p:NuGetAudit=true -p:NuGetAuditMode=all .\NPOI.Core.Test.sln `  was also reporting " warning NU1903: Package 'System.Formats.Asn1' 8.0.0 has a known high severity vulnerability" which was fixed by adding explicit reference and pinnin guiding the restore in projects.
fixes #1394
> Upgrade SixLabors.ImageSharp to version 2.1.9

- main/HSSF/UserModel/HSSFSheet.cs
- main/SS/Util/SheetUtil.cs
maxRows is usefull for AutoSizeColumn and GetColumnWidth from outside the library NPOI.
maxRows was added few years ago (https://github.com/nissl-lab/npoi/pull/723), but it is usefull for AutoSizeColumn and GetColumnWidth in fact.
The change also for AutoSizeColumn is needed in order to respect interface implementation: AutoSizeColumn(column, useMergedCells, maxRows: 0);
> maxRows is usefull for AutoSizeColumn and GetColumnWidth

- .github/workflows/CI.yml
- .github/workflows/PR.yml
- .nuke/build.schema.json
- Directory.Packages.props
- build/Build.GitHubAction.cs
- build/_build.csproj
Now also enabling `cancel-in-progress` for PR workflow which will cancel earlier build if PR is updated.
> Upgrade to NUKE 8.1

- main/SS/Formula/Functions/Rate.cs
- testcases/main/SS/Util/Utils.cs
- testcases/ooxml/SS/Formula/Functions/TestRate.cs
This pretty much updates Rate function to the latest upstream commit.
Testcases are included.
Closes: https://github.com/nissl-lab/npoi/issues/1226
> Backport commits that fix rate function giving incorrect results

- main/SS/Formula/CellEvaluationFrame.cs
- main/SS/Formula/EvaluationTracker.cs
Make test case TestSumif.TestMicrosoftExample1 passed
> fix: Make test case TestSumif.TestMicrosoftExample1 passed

- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
The floowing code generates 2 temp files and is not automatically cleaned. This change fixes the problem.
``` C#
IWorkbook workbook = new SXSSFWorkbook();
var sheet = workbook.CreateSheet();
var row = sheet.CreateRow(0);
row.CreateCell(0).SetCellValue("test");
var sheet2 = workbook.CreateSheet();
var row2 = sheet2.CreateRow(0);
row2.CreateCell(0).SetCellValue("test");
workbook.Dispose();
```
> fixed SXSSFWorkbook can not clear temp files when it called Dispose() on the IWorkbook interface.

- main/SS/UserModel/DateUtil.cs
- testcases/main/SS/UserModel/TestDateUtil.cs
bug 59227: parse dates formatted in Japanese or Chinese. Change javac source encoding from ASCII to UTF-8 (same as build.gradle). Patch from jzhao. This closes #48 on Github.
> bug 59227: parse dates formatted in Japanese or Chinese. 

- main/HSSF/UserModel/HSSFPicture.cs
- testcases/main/POITestCase.cs
- testcases/main/TestPOITestCase.cs
- testcases/openxml4net/TestPackage.cs
- Fix issue found via large corpus tests: HSSFPicture in a HSSFShapeGroup might not have a patriarch set, so let's walk up the parents to try to find one.
- Test for another type of xml-bomb
- use assertStartsWith and assertEndsWith for better unit test error messages
> Patches from poi 3.16

- main/SS/UserModel/ExcelGeneralNumberFormat.cs
We're seeing this _An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll Additional information: Rounding digits must be between 0 and 15, inclusive._ coming from ExcelGeneralNumberFormat [line 98](https://github.com/nissl-lab/npoi/blob/master/main/SS/UserModel/ExcelGeneralNumberFormat.cs#L98). 
This is caused by a wrong data type used in the digits counting algorithm. When calculating the len on [line 96](https://github.com/nissl-lab/npoi/blob/master/main/SS/UserModel/ExcelGeneralNumberFormat.cs#L95):
`int len = (int)Math.Log10((**int**)Math.Abs(value)) + 1;`
Casting a double to an int, you can easily end up with int overflow. When this happens, you end up with len like _-2147483647_.
Numbers higher than 10,000,000,000 are handled correctly [line …
> Fix int overflowing in ExcelGeneralNumberFormat

- benchmarks/NPOI.Benchmarks/DataFormatReadBenchmark.cs
- main/HSSF/UserModel/HSSFCellStyle.cs
- testcases/main/HSSF/UserModel/TestCellStyle.cs
Fixes #1469 by using AsyncLocal for static cache values.
```
BenchmarkDotNet v0.13.12, Windows 10 (10.0.19045.5247/22H2/2022Update)
AMD Ryzen 5 1600X, 1 CPU, 12 logical and 6 physical cores
.NET SDK 9.0.101
[Host]     : .NET 6.0.36 (6.0.3624.51421), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.36 (6.0.3624.51421), X64 RyuJIT AVX2
```
| Method | RowCount | Mean     | Error     | StdDev    |
|------- |--------- |---------:|----------:|----------:|
| Read   | 1000     | 7.045 ms | 0.1364 ms | 0.1675 ms |
| Method | RowCount | Mean     | Error     | StdDev    |
|------- |--------- |---------:|----------:|----------:|
| Read   | 1000     | 9.296 ms | 0.1820 ms | 0.2302 ms |
| Method | RowCount | Mean     | Error     | StdDev    |
|------- |--------- |---------:|----------:|----------:|
| Read   | …
> Inconsistent formatting when reading multiple XLS files concurrently (#1469)

- OpenXmlFormats/Wordprocessing/Table.cs
- ooxml/XWPF/Usermodel/XWPFTableRow.cs
This commit addresses the performance bottleneck in the `CT_Row.Copy` method,
which previously caused significant delays when adding multiple rows to a table.
The issue was particularly noticeable when adding 12 rows, taking over 30 seconds.
Changes made:
- Refactored the `CT_Row.Copy` method to avoid unnecessary deep copying of internal structures.
- Implemented a more efficient row cloning mechanism by reusing shared properties.
Results:
- The time to clone and insert a single row is now consistently under 1 millisecond.
- Adding 12 rows to a table completes in less than 1 milliseconds, compared to the previous 30+ seconds.
This fix significantly improves the performance of table operations, especially for documents with larger tables or frequent row additions.
> Fixes #1472. Optimize CT_Row.Copy to reduce row cloning time under 1ms

- Directory.Build.props
- benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
- main/HPSF/Section.cs
- testcases/Directory.Build.props
This will improve future code quality and existing problems can be handled with new PRs targeting specific warnings that can be then removed from ignore list (NoWarn). As an example invalid exception re-throw in Section.cs now gave compilation error and needed to be fixed before compilation succeeded.
> Reduce warning output during build and treat new warnings as errors

- testcases/main/POIFS/FileSystem/TestOffice2007XMLException.cs
- testcases/main/SS/UserModel/BaseTestWorkbook.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFCell.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFWorkbook.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFColumn.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFSheetColumns.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
- TestXSSFColumn.ZeroWidthTest
- TestXSSFSheet.DefaultColumnStyle
- TestSXSSFWorkbook.SheetdataWriter
- TestSXSSFWorkbook.GzipSheetdataWriter
- TEstXSSFWorkbook.TestBug56957CloseWorkbook
> Fix Unit Test Failures on Windows build server 

- Directory.Build.props
- OpenXmlFormats/Drawing/SpreadsheetPicture.cs
- ooxml/XSSF/UserModel/XSSFTable.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
This will work as a TODO list for improvements which can be tackled in subsequent PRs. Showing couple improvements that the analyzers detected and complained about.
> Enable recommended NET analyzers and suppress errors

- Directory.Build.props
- main/HPSF/Section.cs
- main/HSSF/Record/RecordFactory.cs
- main/POIFS/FileSystem/EntryUtils.cs
- main/POIFS/FileSystem/FilteringDirectoryNode.cs
- ooxml/POIXMLDocumentPart.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- openxml4Net/OPC/Internal/ContentTypeManager.cs
Removing suppressions and fixing problems prohibiting compilation. These are basically performance improvements.
> Fix dictionary usage related analyzer problems

- Directory.Build.props
- main/HSSF/Record/EscherAggregate.cs
- main/HSSF/UserModel/HSSFWorkbook.cs
- main/Polyfills.cs
- main/SS/Format/CellFormatPart.cs
- main/SS/Formula/Atp/AnalysisToolPak.cs
- main/SS/Formula/Eval/Forked/ForkedEvaluationSheet.cs
- main/SS/Formula/Eval/Forked/ForkedEvaluationWorkbook.cs
- main/SS/UserModel/DataFormatter.cs
- main/SS/Util/CellRangeAddressList.cs
- main/SS/Util/Format.cs
- main/SS/Util/SSCellRange.cs
- main/Util/IntMapper.cs
- openxml4Net/OPC/PackageRelationshipCollection.cs
* Use 'string.Contains(char)' instead of 'string.Contains(string)' when searching for a single character
* Type 'XXX' can be sealed because it has no subtypes in its containing assembly and is not externally visible
* To avoid double lookup, call 'TryAdd' instead of calling 'Add' with a 'ContainsKey'
* Prefix generic type parameter name with 'T'
Added polyfill for `Dictionary.TryAdd` and `string.Split(char c, StringSplitOptions options)`
> Fix analyzer reported issues

- main/SS/Util/ImageUtils.cs
Added logic to convert the resolution to "pixels per inch" for images which have it specified as "pixels per meter" or "pixels per centimeter".
> Account for image resolution units other than pixels per inch

- ooxml/XSSF/UserModel/XSSFPatternFormatting.cs
The class used to create conditional a formatting pattern is returning the wrong backing field for the FillForegroundColorColor property (it returns the background instead of the foreground).
> Fix pattern formatting - return correct field for pattern fill foreground

- Directory.Build.props
- main/POIFS/Crypt/DataSpaceMapUtils.cs
- main/POIFS/FileSystem/NPOIFSDocument.cs
- ooxml/XSSF/Extractor/XSSFExportToXml.cs
- ooxml/XSSF/UserModel/Helpers/XSSFRowColShifter.cs
- ooxml/XSSF/UserModel/Helpers/XSSFXmlColumnPr.cs
- ooxml/XSSF/UserModel/XSSFConditionalFormatting.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFTable.cs
- openxml4Net/OPC/PackagingUriHelper.cs
- testcases/main/App.config
- testcases/ooxml/App.config
- testcases/openxml4net/App.config
Also removed some unnecessary binding redirects that were causing annoying warnings while building.
> Remove unnecessary array allocations for Split etc

- ooxml/NPOI.OOXML.Core.csproj
- testcases/ooxml/XSSF/UserModel/TestXSSFName.cs
> Only add dependency to Cryptography.Pkcs when needed

- main/HSSF/UserModel/HSSFCellStyle.cs
- main/SS/UserModel/CellStyle.cs
- main/SS/UserModel/ReadingOrder.cs
- ooxml/XSSF/UserModel/XSSFCellStyle.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFCellStyle.cs
> Implement ICellStyle.ReadingOrder

- main/SS/Format/CellDateFormatter.cs
- main/SS/Format/CellFormat.cs
- main/SS/Format/CellFormatPart.cs
- main/SS/Format/CellFormatType.cs
- main/SS/Format/CellFormatter.cs
- main/SS/Format/CellGeneralFormatter.cs
- main/SS/Format/CellNumberFormatter.cs
- main/SS/Formula/Functions/Mirr.cs
- main/SS/Formula/Functions/MultiOperandNumericFunction.cs
- main/SS/Formula/PTG/AbstractFunctionPtg.cs
- main/SS/UserModel/DataFormatter.cs
- main/SS/Util/Format.cs
- main/Util/Number.cs
- ooxml/XSSF/Streaming/SheetDataWriter.cs
- testcases/main/SS/Formula/Functions/TestMultiOperandNumericFunction.cs
- testcases/main/SS/Formula/PTG/TestAbstractFunctionPtg.cs
- testcases/main/SS/UserModel/TestDataFormatter.cs
- testcases/ooxml/XSSF/Streaming/TestSheetDataWriter.cs
- testcases/ooxml/XSSF/UserModel/TestCloneSheet.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFCell.cs
Main changes:
- [Bug 61246] fix issue where SXSSF sheet data has unicode surrogate chars replaced by '?'
- [Bug 60422] fix data formatter issue with specific format in German locale
- [Bug 58975] do not cast numberOfOperands to byte in AbstractFunctionPtg
- [github-25] support excel number trailing comma format
> Patches from poi 3.17

- OpenXmlFormats/Wordprocessing/Run.cs
#1608 Tested locally, seems to work. 
`AlternativeContent` sections can also contain paragraphs, this is something that might need attention later.
> Fixes #1608, adds support for multiple alternate content sections

- OpenXmlFormats/Drawing/Chart/Chart.cs
In the current version, if you save an xslx document with a chart that has the separator property filled in, the file will be broken when opened in Excel.
This change fixes that.
> Fixed export of chart separator value to xlsx

- OpenXmlFormats/Spreadsheet/AutoFilter.cs
#1616 - Fixes invalid XML for CT_SortCondition.
As per the [spec](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/af08b870-9b06-4812-a4d6-7bc80d819e62) this only writes: 
- `dxfId `when the `sortBy `is either a `fontColor `or `cellColor`
- `iconSet` when the `sortBy` is `icon`
- `iconId` when the `sortBy` is `icon`
> Fix SortCondition XML to match spec rules
