- main/main.csproj
These files were missed in project file. 
Actually, without these files project can't be built since class Complex is used in AnalysisToolPak.cs and classes Code and Rept are used in FunctionEval.cs
> Added three missed files back to the project

- main/HSSF/UserModel/HSSFRow.cs
- main/HSSF/UserModel/HSSFSheet.cs
- main/HSSF/UserModel/HSSFWorkbook.cs
- main/SS/UserModel/Row.cs
- main/SS/UserModel/Sheet.cs
- main/SS/UserModel/Workbook.cs
- ooxml/XSSF/UserModel/XSSFDialogsheet.cs
- ooxml/XSSF/UserModel/XSSFRow.cs
- ooxml/XSSF/UserModel/XSSFSheet.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
Then we can query them with LINQ :)
> Make IWorkbook, ISheet and IRow extends IEnumerable<>

- main/SS/SpreadsheetVersion.cs
Added default file extension information to SpreadsheetVersion
> Added default file extension information

- main/SS/UserModel/DataFormatter.cs
- main/SS/UserModel/DateUtil.cs
- main/SS/UserModel/ExcelStyleDateFormatter.cs
- main/SS/Util/Format.cs
- testcases/main/SS/UserModel/TestDataFormatter.cs
tests which verify the new formatting options.
> Bug 54786: Fix missing quoting in date formatting, add a number of unit

- examples/xssf/LineChart/Program.cs
Updated LineChart example: correctly call some methods for Axes manipulation
> Patch for LineChart example

- testcases/main/SS/UserModel/BaseTestConditionalFormatting.cs
Maybe, it was caused by commit 2558859c.
> Fix: Building "NPOI.TestCases" project was failed.

- main/SS/UserModel/DataFormatter.cs
In Java, the output of "0.#####" and "#.#####" are the same.
In C#, "0.#####" has the same output as Java,
"#.#####" does not display "0", or when it is less than 1, 0 immediately before the decimal point is not displayed.
For compatibility it should be "0.#####".
```java
import java.text.DecimalFormat;
public class DecimalFormatSample {
public static void main(String args[]) {
DecimalFormat[] decimalFormats = new DecimalFormat[]{
new DecimalFormat("#.#####"),
new DecimalFormat("0.#####"),
new DecimalFormat("#"),
new DecimalFormat("0"),
};
double[] v = new double[]{
0.0,
0.0000002,
0.01,
0.1,
0.100,
0.4,
0.400,
0.5,
0.999999999999,
1.0,
1.1,
12.0,
123.4,
123.400,
};
for(int i=0; i< decimalFormats.length; i++){
for(int j=0; j< v.length; j++){
System.out.println( decimalFormats[ i ].format( …
```
> generalDecimalNumFormat should be "0.##########".

- examples/NPOI.XWPF.Examples.2017.sln
- examples/xwpf/CreateBullet/Program.cs
- examples/xwpf/CreateOMathFormula/App.config
- examples/xwpf/CreateOMathFormula/CreateOMathFormula.csproj
- examples/xwpf/CreateOMathFormula/Program.cs
- examples/xwpf/CreateOMathFormula/Properties/AssemblyInfo.cs
- examples/xwpf/SimpleDocument/Program.cs
- examples/xwpf/SimpleTable/Program.cs
- examples/xwpf/UpdateEmbeddedDoc/Program.cs
- examples/xwpf/UpdateEmbeddedDoc/UpdateEmbeddedDoc.csproj
- examples/xwpf/UpdateEmbeddedDoc/packages.config
- ooxml/NPOI.OOXML.csproj
- ooxml/OpenXmlFormats/NPOI.OpenXmlFormats.csproj
- ooxml/OpenXmlFormats/Shared/IOMathContainer.cs
- ooxml/OpenXmlFormats/Shared/Math.cs
- ooxml/OpenXmlFormats/Wordprocessing/Paragraph.cs
- ooxml/OpenXmlFormats/Wordprocessing/Table.cs
- ooxml/XWPF/Usermodel/MathContainer.cs
- ooxml/XWPF/Usermodel/XWPFAcc.cs
- ooxml/XWPF/Usermodel/XWPFF.cs
- ooxml/XWPF/Usermodel/XWPFNary.cs
- ooxml/XWPF/Usermodel/XWPFOMath.cs
- ooxml/XWPF/Usermodel/XWPFOMathArg.cs
- ooxml/XWPF/Usermodel/XWPFParagraph.cs
- ooxml/XWPF/Usermodel/XWPFRun.cs
- ooxml/XWPF/Usermodel/XWPFSSub.cs
- ooxml/XWPF/Usermodel/XWPFSharedRun.cs
- ooxml/XWPF/Usermodel/XWPFTableCell.cs
Please update nuget package with this features.
>  Added methods for set top, left, right border at cell. Implemented OMath formula edit/creation with example.

- main/NPOI.csproj
- main/SS/Formula/Atp/AnalysisToolPak.cs
- main/SS/Formula/Functions/Averageif.cs
- main/SS/Formula/Functions/Averageifs.cs
- main/SS/Formula/Functions/Countif.cs
- testcases/main/NPOI.TestCases.csproj
- testcases/main/SS/Formula/Functions/TestAverageif.cs
- testcases/main/SS/Formula/Functions/TestAverageifs.cs
This change implements AVERAGEIFS and AVERAGEIF functions from AnalysisToolPak
> AVERAGEIF and AVERAGEIFS functions

- main/Util/TempFile.cs
> use guid not random

- main/HSSF/UserModel/HSSFCell.cs
- main/HSSF/UserModel/HSSFWorkbook.cs
- main/SS/UserModel/Workbook.cs
- ooxml/XSSF/Streaming/SXSSFCell.cs
- ooxml/XSSF/Streaming/SXSSFSheet.cs
- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
- ooxml/XSSF/UserModel/XSSFCell.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
Implemented SXSSFCell method setting DateTime cell value. Fixed and unified getting workbook date system.
> Fix setting DateTime cell value for SXSSFCell

- ooxml/XSSF/UserModel/XSSFWorkbook.cs
Functionality added to work book to allow the removal of PivotTables.  Also removes any PivotCacheDefintions.
> Remove PivotTables and PivotCache definitions.

- OpenXmlFormats/Spreadsheet/Sheet/CT_CommentList.cs
- main/HSSF/UserModel/HSSFCellStyle.cs
- main/SS/UserModel/ExtendedColor.cs
- main/SS/Util/DateFormatConverter.cs
- main/Util/CodePageUtil.cs
- main/Util/HexDump.cs
- ooxml/XSSF/Model/CommentsTable.cs
- ooxml/XSSF/Model/ThemesTable.cs
- ooxml/XSSF/Streaming/SXSSFRow.cs
- ooxml/XSSF/UserModel/XSSFFactory.cs
- ooxml/XWPF/Usermodel/XWPFFactory.cs
- testcases/main/HSSF/UserModel/TestBugs.cs
- testcases/main/HSSF/UserModel/TestCellStyle.cs
- testcases/main/HSSF/UserModel/TestHSSFWorkbook.cs
- testcases/main/POIFS/FileSystem/TestNPOIFSFileSystem.cs
- testcases/main/SS/UserModel/BaseTestWorkbook.cs
- testcases/ooxml/XSSF/Model/TestThemesTable.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFSheetAutoSizeColumn.cs
> Fix some bugs.

- main/HSSF/UserModel/HSSFWorkbook.cs
- main/SS/UserModel/Workbook.cs
- ooxml/XSSF/Streaming/SXSSFCell.cs
- ooxml/XSSF/Streaming/SXSSFWorkbook.cs
- ooxml/XSSF/Streaming/SheetDataWriter.cs
- ooxml/XSSF/UserModel/XSSFWorkbook.cs
- testcases/main/SS/UserModel/BaseTestWorkbook.cs
- testcases/ooxml/XSSF/Streaming/TestSXSSFWorkbook.cs
Provide generic sheet enumerator for IWorkbook, add SXSSFSheet enumerator of SXSSFWorkbook
> Provide generic sheet enumerator for IWorkbook

- main/SS/Formula/Functions/Text/Substitute.cs
This prevents an infinite loop in the subsequent while loop.
Same check as in ReplaceOneOccurrence. fixes #225
> Added check for empty searchStr in ReplaceAllOccurrences.

- ooxml/XWPF/Usermodel/XWPFStyles.cs
see https://poi.apache.org/apidocs/dev/org/apache/poi/xwpf/usermodel/XWPFStyles.html#getStyleWithSameName-org.apache.poi.xwpf.usermodel.XWPFStyle-
> Add XWPFStyles.GetStyleWithName(string styleName)

- main/SS/Formula/Functions/Match.cs
In case the lookupRange area is not sorted, still try to get the right index
> fix Match function for compatible

- OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotTableDefinition.cs
- OpenXmlFormats/Spreadsheet/Workbook/CT_PivotCache.cs
Hi @tony1223, I found a couple more missteps. Stumbled across them while working with PowerPivot.
> Fix structure CT_PivotTableDefinition and CT_PivotCache

- main/SS/Formula/Atp/RandBetween.cs
Changed cast from int to long.
Removed unneeded parentheses.
#891
> Fixed RandBetween

- OpenXmlFormats/NPOI.OpenXmlFormats.Core.csproj
- main/NPOI.Core.csproj
- ooxml/NPOI.OOXML.Core.csproj
- openxml4Net/NPOI.OpenXml4Net.Core.csproj
Removing references that are not actually needed by the code.
> Remove unused package references

- main/NPOI.Core.csproj
> Update MathNet.Numerics (v5)

- OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
Fixes #1234 
Fix The Style with index 0 does not write.
> fix: Do not save Style with index 0

- OpenXmlFormats/Wordprocessing/Settings.cs
This PR fixing saving docx file in compatibility mode 
Closes #882
> Fix saving docx in compatibility mode

- main/SS/UserModel/IndexedColors.cs
Fix typo olivergreen in IndexedColors. Closes #1256
> Fix typo olivergreen in IndexedColors

- ooxml/XSSF/UserModel/XSSFRichTextString.cs
- testcases/ooxml/XSSF/UserModel/TestXSSFRichTextString.cs
> Fix XSSFRichTextString.ApplyFont

- main/NPOI.Core.csproj
Closes https://github.com/nissl-lab/npoi/issues/1149
> Update SharpZipLib to v1.4.2

- ooxml/XSSF/UserModel/XSSFDataValidation.cs
> Fix EncodeUtf method

- Directory.Build.props
- Directory.Packages.props
- benchmarks/NPOI.Benchmarks/NPOI.Benchmarks.csproj
- build/_build.csproj
- main/NPOI.Core.csproj
- ooxml/NPOI.OOXML.Core.csproj
- solution/NPOI.Core.Test.sln
- testcases/main/NPOI.TestCases.Core.csproj
- testcases/ooxml/NPOI.OOXML.TestCases.Core.csproj
- testcases/openxml4net/NPOI.OOXML4Net.TestCases.Core.csproj
Single place to specify used dependency versions, see https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management .
> Convert to use Central Package Management

- main/SS/HtmlDocumentFacade.cs
fix https://github.com/nissl-lab/npoi/issues/1381
> fix: AddStyleClass no update newClassValue

- OpenXmlFormats/Spreadsheet/Sheet/CT_Cell.cs
This PR fixes checking if cell style is set
> Fix checking if cell style is set

- Directory.Packages.props
fix #1427
Upgrade System.Security.Cryptography.Pkcs to 8.0.1
Upgrade System.Security.Cryptography.Xml to 8.0.2
> Update version of System.Security.Cryptography

- main/SS/Formula/Atp/XLookupFunction.cs
- main/SS/Formula/Eval/AreaEval.cs
- main/SS/Formula/Eval/AreaEvalBase.cs
- main/SS/Formula/Eval/FunctionEval.cs
- main/SS/Formula/Functions/AggregateFunction.cs
- main/SS/Formula/Functions/Count.cs
- main/SS/Formula/Functions/Counta.cs
- main/SS/Formula/Functions/Frequency.cs
- main/SS/Formula/Functions/StatsLib.cs
- main/SS/Formula/Functions/Subtotal.cs
- main/SS/Formula/TwoDEval.cs
- testcases/main/SS/Formula/Functions/TestFrequency.cs
- testcases/main/SS/Formula/Functions/TestSubtotal.cs
[POI 66093](https://bz.apache.org/bugzilla/show_bug.cgi?id=66093) add support for unimplemented subfunctions to SUBTOTAL function
[POI 62373](https://bz.apache.org/bugzilla/show_bug.cgi?id=62373) Support FREQUENCY function
Some improvements for issue #1023
> [POI 66093 & POI 62373] Support FREQUENCY function and subfunctions to SUBTOTAL function

- ooxml/XWPF/Usermodel/XWPFTable.cs
- testcases/ooxml/XWPF/UserModel/TestXWPFTable.cs
> Add XWPFTable.NumberOfColumns

- Directory.Packages.props
- ooxml/NPOI.OOXML.Core.csproj
> Remove System.Security.Cryptography.Pkcs

- OpenXmlFormats/Drawing/BaseTypes.cs
- OpenXmlFormats/Drawing/SpreadsheetDrawing.cs
- OpenXmlFormats/Drawing/WordprocessingDrawing.cs
> Fix CT_Point2D xml node prefix issue

- main/SS/Formula/Atp/XLookupFunction.cs
- main/SS/Formula/Eval/RelationalOperationEval/RelationalOperationEval.cs
- main/SS/Formula/Eval/TwoOperandNumeric/TwoOperandNumericOperation.cs
- main/SS/Formula/Functions/ArrayFunction.cs
- main/SS/Formula/Functions/Boolean/BooleanFunction.cs
- main/SS/Formula/OperationEvaluatorFactory.cs
- main/SS/Formula/UserDefinedFunction.cs
- testcases/main/SS/Formula/Functions/TestOrFunction.cs
> bug-65915 add test for 'OR' function

- Directory.Packages.props
- ooxml/XSSF/UserModel/XSSFSheet.cs
> Call GetColumnHelper() to make sure columnHelper is initialized 

- ooxml/XSSF/UserModel/XSSFDataValidationConstraint.cs
> Encode formula string while double quotes are added before and after 
